add LongAtomTest
cortinico/docker-java8-32bit pull request #1
Opened 2018-05-02 11:45 UTC by reymont

Add LongAtomTest example to display the usage of volatile.

2018-05-06 22:24 UTC, cortinico requested changes
Thanks for the PR <3
Here just a couple of comments ;)

2018-05-06 22:24 UTC, cortinico commented on README.md
> +## Run LongAtomTest example
Can you change this to 

```
## How to run a sample Java File
```

2018-05-06 22:24 UTC, cortinico commented on README.md
> +
Can you add a bit of description here, like:

```
Let's try to run a sample .java file inside the docker container. You can use a sample java file, LongAtomTest.java, pasted below.
```

2018-05-07 01:45 UTC, reymont commented
the comments has changed.

2018-05-07 12:39 UTC, merged